default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
   # ref: https://github.com/mperham/sidekiq/issues/2985#issuecomment-531097962
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>
  # frequency in seconds to periodically run the Reaper, which attempts
  # to find and recover connections from dead threads
  reaping_frequency: <%= ENV.fetch('DB_POOL_REAPING_FREQUENCY', 30) %>
  variables:
    # we are setting this value to be close to the racktimeout value. we will iterate and reduce this value going forward
    statement_timeout: <%= ENV["POSTGRES_STATEMENT_TIMEOUT"] || "14s" %>

development:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_dev') %>"
    username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
    password: "<%= ENV.fetch('POSTGRES_PASSWORD', '') %>"
    migrations_paths: db/migrate
  
  shopify:
    <<: *default
    # Local test için: host.docker.internal:5433 (local PostgreSQL)
    # Supabase için: SHOPIFY_DB_HOST=db.hkoawgewdmqgadwuxozv.supabase.co SHOPIFY_DB_PORT=6543
    host: <%= ENV.fetch('SHOPIFY_DB_HOST', 'aws-1-eu-west-1.pooler.supabase.com') %>
    port: <%= ENV.fetch('SHOPIFY_DB_PORT', '6543') %>
    database: "<%= ENV.fetch('SHOPIFY_DB_DATABASE', 'postgres') %>"
    username: "<%= ENV.fetch('SHOPIFY_DB_USERNAME', 'postgres.hkoawgewdmqgadwuxozv') %>"
    password: "<%= ENV.fetch('SHOPIFY_DB_PASSWORD', '74a5cf511f2Ecdf70e') %>"
    connect_timeout: 30
    sslmode: <%= ENV.fetch('SHOPIFY_DB_SSLMODE', 'require') %>
    prepared_statements: false
    statement_timeout: 15000
    migrations_paths: db/shopify_migrate

test:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_test') %>"
    username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
    password: "<%= ENV.fetch('POSTGRES_PASSWORD', '') %>"
  
  shopify:
    <<: *default
    host: <%= ENV.fetch('SHOPIFY_DB_HOST', 'localhost') %>
    port: <%= ENV.fetch('SHOPIFY_DB_PORT', '5432') %>
    database: "<%= ENV.fetch('SHOPIFY_DB_DATABASE', 'shopify_test') %>"
    username: "<%= ENV.fetch('SHOPIFY_DB_USERNAME', 'postgres') %>"
    password: "<%= ENV.fetch('SHOPIFY_DB_PASSWORD', '') %>"

production:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_production') %>"
    username: "<%= ENV.fetch('POSTGRES_USERNAME', 'chatwoot_prod') %>"
    password: "<%= ENV.fetch('POSTGRES_PASSWORD', 'chatwoot_prod') %>"
    migrations_paths: db/migrate
  
  shopify:
    <<: *default
    host: <%= ENV.fetch('SHOPIFY_DB_HOST', 'aws-1-eu-west-1.pooler.supabase.com') %>
    port: <%= ENV.fetch('SHOPIFY_DB_PORT', '6543') %>
    database: "<%= ENV.fetch('SHOPIFY_DB_DATABASE', 'postgres') %>"
    username: "<%= ENV.fetch('SHOPIFY_DB_USERNAME', 'postgres.hkoawgewdmqgadwuxozv') %>"
    password: "<%= ENV.fetch('SHOPIFY_DB_PASSWORD', '74a5cf511f2Ecdf70e') %>"
    connect_timeout: 30
    sslmode: require
    prepared_statements: false
    statement_timeout: 15000
    migrations_paths: db/shopify_migrate
